Mooc_video/urls.py
from django.urls import path, include
from django.contrib import admin
from apps.student import views as stuViews
from apps.teacher import views as tchViews
from apps.index import views as indexViews

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', indexViews.redirect_home, name='home'),

    path('index/', include(
        [path('stu_login/', indexViews.stu_login_view),
         path('submit_stu_login/', indexViews.stu_login),
         path('tch_login/', indexViews.tch_login_view),
         path('submit_tch_login/', indexViews.tch_login),
         path('log_out/', indexViews.log_out, name='log_out')
         ]
    )),

    path('teacher/', include(
        [path('index/', tchViews.index, name='tch_index'),
         path('create_course/', tchViews.create_course, name='tch_create_course'),
         path('submit_course/', tchViews.new_course, name='submit_course'),
         path('manage_course/', tchViews.course_list, name='tch_course_list'),
         path('profile/', tchViews.user_profile, name='tch_profile'),
         path('all_course/', tchViews.search_course, name='tch_search_cour'),
         path('find_someone/', tchViews.search_user, name='tch_search_user'),
         path('edit_course_info/<int:id>', tchViews.edit_course_info),
         path('course_info/<int:id>/', tchViews.course_info, name='course_info'),
         path('update_course/', tchViews.update_course, name='update_course'),
         path('add_section/<int:id>/<str:name>/', tchViews.add_section_view, name='add_section'),
         path('edit_section_info/<int:id>/', tchViews.edit_section_view),
         path('submit_section/', tchViews.add_setion, name='submit_section'),
         path('update_section/', tchViews.update_section),
         path('upload/', tchViews.upload_file),
         path('reupload/', tchViews.reupload_file),
         path('cour_image/', tchViews.cour_image),
         path('learn_detail/<int:ls_id>/', tchViews.learn_status_details),

         path('delete_course/', tchViews.delete_course),
         path('delete_section/', tchViews.delete_section),

         path('get_learn_list/<int:id>/', tchViews.get_stu_by_cour, name='get_learn_list'),
         path('get_section_list/<int:id>/', tchViews.get_sect_by_cour, name='get_section_list'),

         path('get_index_chart/', tchViews.get_index_chart_data),
         path('get_stu_top10_chart/<int:cour_id>/', tchViews.get_stu_top10_chart),
         path('get_last_week_chart/<int:cour_id>/', tchViews.get_last_week_chart)
         ]
    )),

    path('student/', include(
        [path('index/', stuViews.index, name='stu_index'),
         path('my_course/<int:page>/', stuViews.my_course, name='my_course'),
         path('search_course/<int:page>/', stuViews.search_course, name='stu_search_course'),
         path('search_course/<int:page>/<str:info>/', stuViews.search_course_by_info),
         path('search_user/', stuViews.search_user, name='stu_search_user'),
         path('profile/', stuViews.profile, name='stu_profile'),
         path('show_cour_info/<int:id>/', stuViews.show_cour_info),
         path('join_course/', stuViews.join_course),
         path('quit_course/', stuViews.quit_course),
         path('course_page/<int:id>/', stuViews.course_page),
         path('learn/<int:sect_id>/', stuViews.learn_view, name='stu_learn'),
         path('show_cour_detail/<int:id>/', stuViews.show_cour_detail),

         path('get_learned_sect/', stuViews.get_learned_sect),
         path('finished/', stuViews.finish_sect),
         path('get_recommend/', stuViews.get_recommend)
         ]
    )),
]

apps/index/models.py
from django.db import models


class NepUniversity(models.Model):
    univ_name = models.CharField('university name', max_length=30, default='unknow')
    univ_city = models.CharField('university city', max_length=10, default='unknow')
    univ_description = models.CharField('description', max_length=100, null=True)

    class Meta:
        managed = True
        db_table = 'nep_university'


class NepCourse(models.Model):
    COURSE_TYPE = {
        ('0', '哲学'),
        ('1', '经济学'),
        ('2', '法学'),
        ('3', '教育学'),
        ('4', '文学'),
        ('5', '历史学'),
        ('6', '理学'),
        ('7', '工学'),
        ('8', '农学'),
        ('9', '医学'),
        ('10', '管理学'),
        ('11', '艺术学'),
        ('12', '军事学'),
        ('13', '其他')
    }

    cour_name = models.CharField(max_length=45)   #
    cour_type = models.CharField(default='unknow', max_length=10, choices=COURSE_TYPE)   #
    cour_start = models.DateTimeField(null=True)   #
    cour_end = models.DateTimeField(null=True)    #
    cour_dir = models.CharField(max_length=45, null=True)
    cour_create_tch = models.ForeignKey('teacher.NepTeacher', models.CASCADE)    #
    cour_avilable = models.BooleanField(default=True)
    cour_description = models.TextField(null=True)     #
    cour_univ = models.ForeignKey('index.NepUniversity', models.SET_NULL, null=True)   #
    cour_create_time = models.DateTimeField(null=True)  #
    cour_image = models.ImageField(null=True, default='default.png')

    class Meta:
        managed = True
        db_table = 'nep_course'


class NepSection(models.Model):
    sect_name = models.CharField(max_length=50)
    sect_text = models.CharField(max_length=500, null=True)
    sect_media = models.CharField(max_length=200, null=True)
    sect_cour = models.ForeignKey(NepCourse, models.CASCADE)
    sect_teacher = models.ForeignKey('teacher.NepTeacher', models.CASCADE)
    sect_tag = models.CharField(max_length=20, default='1-1')
    sect_create_time = models.DateTimeField(null=True)

    class Meta:
        managed = True
        db_table = 'nep_section'


class NepLearnStatus(models.Model):
    student = models.ForeignKey('student.NepStudent', models.CASCADE)
    course = models.ForeignKey(NepCourse, models.CASCADE)
    percentage = models.IntegerField(default=0)
    start_time = models.DateTimeField()
    last_time = models.DateTimeField(null=True)
    learn_frequency = models.IntegerField(default=0, null=True)

    class Meta:
        managed = True
        db_table = 'nep_learn_status'


class NepSectionStatus(models.Model):
    student = models.ForeignKey('student.NepStudent', models.CASCADE)
    course = models.ForeignKey(NepCourse, models.CASCADE)
    section = models.ForeignKey(NepSection, models.CASCADE)
    start_time = models.DateTimeField(null=True)
    last_time = models.DateTimeField(null=True)
    completed = models.BooleanField(default=False)
    view_time = models.TimeField(null=True)

    class Meta:
        managed = True
        db_table = 'nep_section_status'

apps/student/models.py
from django.db import models


class NepStudent(models.Model):
    password = models.CharField(max_length=50, default='password')
    stu_name = models.CharField(max_length=45, null=True)
    stu_mobile = models.CharField(unique=True, max_length=15)
    stu_recommend_cour_info = models.CharField(max_length=30, null=True)
    stu_graduate_date = models.DateField(max_length=15, null=True)
    stu_univ = models.ForeignKey('index.NepUniversity', models.SET_NULL, null=True)
    stu_last_login_time = models.DateTimeField(null=True, default='2020-01-01 00:00:00')
    stu_last_login_ip = models.CharField(max_length=30, null=True, default='0.0.0.0')
    stu_profile = models.CharField(max_length=200, null=True)
    stu_register_time = models.DateTimeField(null=True)

    class Meta:
        managed = True
        db_table = 'nep_student'

apps/student/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from index.models import NepCourse, NepLearnStatus, NepSection
from .controller.course import Course
from .controller.allStatus import *
from .controller.recommend import *
import random


# Create your views here.

def index(request):
    cour_list = NepCourse.objects.order_by('?')[:5]
    content = {'class_my_course': '',
               'class_search_course': '',
               'class_search_user': '',
               'class_profile': '',
               'cour_list': cour_list}
    return render(request, 'student/index.html', content)


def get_recommend(request):
    res = get_cloest(int(request.COOKIES['stu_id']))
    cour_list = []
    print(res)
    for each_id in res:
        cour_list.append(NepCourse.objects.get(pk=each_id[0]))
    return render(request, 'student/recommend.html', {'cour_list': cour_list})


def my_course(request, page=1):
    cour_obj = Course()
    stu_id = request.COOKIES['stu_id']
    content = {'class_my_course': 'layui-this',
               'class_search_course': '',
               'class_search_user': '',
               'class_profile': '',
               'item_number': cour_obj.get_item_number(stu_id=stu_id),
               'cour_list': cour_obj.stu_cour(number=4, page=page, stu_id=stu_id)}

    return render(request, 'student/my_course.html', content)


def search_course(request, page=1):
    search_obj = Course()
    content = {'class_my_course': '',
               'class_search_course': 'layui-this',
               'class_search_user': '',
               'class_profile': '',
               'item_number': search_obj.get_item_number(),
               'cour_list': search_obj.all_course(number=6, page=page)}
    return render(request, 'student/new_course.html', content)


def search_user(request):
    content = {'class_my_course': '',
               'class_search_course': '',
               'class_search_user': 'layui-this',
               'class_profile': ''}
    return render(request, 'student/empty.html', content)


def profile(request):
    content = {'class_my_course': '',
               'class_search_course': '',
               'class_search_user': '',
               'class_profile': 'layui-this'}
    return render(request, 'student/empty.html', content)


def show_cour_info(request, id):
    cour_obj = Course(id=id)
    return JsonResponse(cour_obj.get_cour_info())

def show_cour_detail(request, id):
    cour_obj = NepCourse.objects.get(pk=id)
    content = {'cour': cour_obj,
               'stu_num': NepLearnStatus.objects.filter(course_id=id).count(),
               'sect_num': NepSection.objects.filter(sect_cour_id=id).count()}
    return render(request, 'student/course_detail.html', content)

def join_course(request):
    result = new_status(id_stu=request.COOKIES['stu_id'], id_cour=request.POST['id_cour'])
    print(result)
    return JsonResponse(result)

def quit_course(request):
    result = quit_cour(id_stu=request.COOKIES['stu_id'], id_course=request.POST['cour_id'])
    print(result)
    return JsonResponse(result)

def course_page(request, id):
    content = {'class_my_course': 'layui-this',
               'class_search_course': '',
               'class_search_user': '',
               'class_profile': ''}
    if not NepCourse.objects.get(pk=id).cour_avilable:
        content['cour_id'] = id
        return render(request, 'student/course_not_avai.html', content)
    else:
        content['cour_obj'] = NepCourse.objects.get(pk=id)
        content['ls_obj'] = NepLearnStatus.objects.get(course_id=id, student_id=request.COOKIES['stu_id'])
        content['section_list'] = NepSection.objects.filter(sect_cour_id=id).order_by('sect_tag')
        return render(request, 'student/course_page.html', content)

def get_learned_sect(request):
    stu_id = request.COOKIES['stu_id']
    return JsonResponse(get_learned(cour_id=request.POST['cour_id'], stu_id=stu_id))

def learn_view(request, sect_id):
    stu_id = request.COOKIES['stu_id']
    sect_obj = NepSection.objects.get(pk=sect_id)
    content = {'class_my_course': 'layui-this',
               'class_search_course': '',
               'class_search_user': '',
               'class_profile': '',
               'sect_tag': sect_obj.sect_tag,
               'sect_name': sect_obj.sect_name,
               'sect_text': sect_obj.sect_text,
               'sect_media': sect_obj.sect_media,
               'cour_id': sect_obj.sect_cour_id
               }
    before_learn(sect_id=sect_id, stu_id=stu_id)

    return render(request, 'student/learning.html', content)

def finish_sect(request):
    stu_id = request.COOKIES['stu_id']
    json_return = finish_sect_handler(sect_id=request.POST['sect_id'], stu_id=stu_id)
    return JsonResponse(json_return)

def search_course_by_info(request, info='', page=1):
    search_obj = Course()
    content = {'class_my_course': '',
               'class_search_course': 'layui-this',
               'class_search_user': '',
               'class_profile': '',
               'item_number': search_obj.get_item_number(info=info),
               'cour_list': search_obj.all_course(number=6, page=page, info=info)}
    return render(request, 'student/new_course.html', content)

templates/student/course_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
</head>

<body>
{% csrf_token %}
<div class="layui-bg-gray">
    <div class="layui-row layui-col-space12" style="padding: 10px;">
        <div class="layui-col-md12">
            <div class="layui-card">
                <div class="layui-card-body">
                    <fieldset class="layui-elem-field layui-field-title">
                        <legend>课程信息</legend>
                    </fieldset>
                    <div class="layui-row layui-col-space3">
                        <div class="layui-col-md2">
                            课程名称
                        </div>
                        <div class="layui-col-md10">
                            {{ cour.cour_name }}
                        </div>

                        <div class="layui-col-md2">
                            分类信息
                        </div>
                        <div class="layui-col-md10">
                            {{ cour.get_cour_type_display }}
                        </div>

                        <div class="layui-col-md2">
                            创建教师
                        </div>
                        <div class="layui-col-md10">
                            {{ cour.cour_create_tch.tch_name }}
                        </div>

                        <div class="layui-col-md2">
                            开始时间
                        </div>
                        <div class="layui-col-md10">
                            {{ cour.cour_start }}
                        </div>

                        <div class="layui-col-md2">
                            结束时间
                        </div>
                        <div class="layui-col-md10">
                            {{ cour.cour_end }}
                        </div>

                        <div class="layui-col-md2">
                            参加人数
                        </div>
                        <div class="layui-col-md10">
                            {{ stu_num }}
                        </div>

                        <div class="layui-col-md2">
                            章节数目
                        </div>
                        <div class="layui-col-md10">
                            {{ sect_num }}
                        </div>

                        <div class="layui-col-md2">
                            课程简介
                        </div>
                        <div class="layui-col-md10">
                            {{ cour.cour_description }}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

</body>

<script src="{% static 'layui/layui.all.js' %}"></script>
<script src="{% static 'assets/js/layui/learn_detail_table.js' %}"></script>

</html>

templates/student/course_not_avai.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
</head>

<body>
<div class="layui-layout layui-layout-admin">

    {#    TOP NAV#}
    {% include 'nav/top_nav_stu.html' %}
    {#    TOP NAV#}

    {#    LEFT NAV#}
    {% include 'nav/left_nav_stu.html' %}
    {#    LEFT NAV#}

    <div class="layui-body">
        <div style="padding: 10px">
            <fieldset class="layui-elem-field layui-field-title">
                <legend>课程不可用</legend>
            </fieldset>

            <blockquote class="layui-elem-quote">创建该课程的教师已经锁定该课程，目前尚不可学习</blockquote>
        </div>
    </div>
</div>

<script src="{% static 'assets/js/jquery-1.10.2.js' %}"></script>
<script src="{% static 'assets/js/jquery.metisMenu.js' %}"></script>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script src="{% static 'assets/js/custom-scripts.js' %}"></script>
<script src="{% static 'assets/js/layui/nav.js' %}"></script>
</body>

</html>

templates/student/course_page.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
    <link rel="stylesheet" href="{% static 'assets/css/layout/card_list.css' %}"/>
    <link rel="stylesheet" href="{% static 'assets/css/layout/cour_info.css' %}">
</head>

<body>
<div class="layui-layout layui-layout-admin">

    {#    TOP NAV#}
    {% include 'nav/top_nav_stu.html' %}
    {#    TOP NAV#}

    {#    LEFT NAV#}
    {% include 'nav/left_nav_stu.html' %}
    {#    LEFT NAV#}

    <div class="layui-body layui-bg-gray">
        <div class="layui-fluid">
            <div class="layui-row layui-col-space12">
                <div class="layui-col-md4">
                    <div class="layui-card top-card">
                        <div class="layui-card-header">
                            课程详情
                        </div>
                        <div class="layui-card-body">
                            <div class="layui-col-md4">
                                课程名称
                            </div>
                            <div class="layui-col-md8">
                                {{ cour_obj.cour_name }}
                            </div>

                            <div class="layui-col-md4">
                                分类信息
                            </div>
                            <div class="layui-col-md8">
                                {{ cour_obj.get_cour_type_display }}
                            </div>

                            <div class="layui-col-md4">
                                创建教师
                            </div>
                            <div class="layui-col-md8">
                                {{ cour_obj.cour_create_tch.tch_name }}
                            </div>

                            <div class="layui-col-md4">
                                开始时间
                            </div>
                            <div class="layui-col-md8">
                                {{ cour_obj.cour_start }}
                            </div>

                            <div class="layui-col-md4">
                                结束时间
                            </div>
                            <div class="layui-col-md8">
                                {{ cour_obj.cour_end }}
                            </div>

                            <div class="layui-col-md4">
                                课程简介
                            </div>
                            <div class="layui-col-md8">
                                {{ cour_obj.cour_description }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="layui-col-md4">
                    <div class="layui-card top-card">
                        <div class="layui-card-header">
                            我的学习情况
                        </div>
                        <div class="layui-card-body">
                            <div class="layui-col-md4">
                                完成百分比
                            </div>
                            <div class="layui-col-md8">
                                {{ ls_obj.percentage }}%
                            </div>
                            <div class="layui-col-md4">
                                上次学习时间
                            </div>
                            <div class="layui-col-md8">
                                {{ ls_obj.last_time }}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="layui-col-md4">
                    <div class="layui-card top-card">
                        <div class="layui-card-header">
                            课程操作
                        </div>
                        <div class="layui-card-body">
                            {% csrf_token %}
                            <button type="button" class="layui-btn layui-btn-danger" onclick="quit({{ cour_obj.id }})">退选课程</button>
                        </div>
                    </div>
                </div>
            </div>

            <div style="padding: 10px">
                <fieldset class="layui-elem-field layui-field-title">
                    <legend>全部章节</legend>
                </fieldset>
            </div>

            {#            <div class="layui-fluid">#}
            <div class="layui-row layui-col-space12">
                <div class="layui-col-md12">
                    {% csrf_token %}
                    {% for each in section_list %}
                        <div class="layui-card sect-item"
                             onclick="window.location.href='{% url 'stu_learn' sect_id=each.id %}'">
                            <div class="layui-card-header" id="header_{{ each.id }}">
                                [{{ each.sect_tag }}]
                            </div>
                            <div class="layui-card-body">
                                {{ each.sect_name }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'assets/js/jquery-1.10.2.js' %}"></script>
<script src="{% static 'assets/js/jquery.metisMenu.js' %}"></script>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script src="{% static 'assets/js/layui/stu_cour_page.js' %}"></script>
{#<script src="{% static 'assets/js/layui/nav.js' %}"></script>#}
</body>

</html>

templates/student/empty.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
</head>

<body>
<div class="layui-layout layui-layout-admin">

    {#    TOP NAV#}
    {% include 'nav/top_nav_stu.html' %}
    {#    TOP NAV#}

    {#    LEFT NAV#}
    {% include 'nav/left_nav_stu.html' %}
    {#    LEFT NAV#}

    <div class="layui-body">
        <div style="padding: 10px">

        </div>
    </div>
</div>

<script src="{% static 'assets/js/jquery-1.10.2.js' %}"></script>
<script src="{% static 'assets/js/jquery.metisMenu.js' %}"></script>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script src="{% static 'assets/js/layui/nav.js' %}"></script>
</body>

</html>

templates/student/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
    <link rel="stylesheet" href="{% static 'assets/css/layout/index_page.css' %}">
</head>

<body>
<div class="layui-layout layui-layout-admin">

    {#    TOP NAV#}
    {% include 'nav/top_nav_stu.html' %}
    {#    TOP NAV#}

    {#    LEFT NAV#}
    {% include 'nav/left_nav_stu.html' %}
    {#    LEFT NAV#}

    <div class="layui-body layui-bg-gray">
        {% csrf_token %}
        <div class="layui-fluid">
            <div class="layui-row layui-col-space12">
                <div class="layui-col-md12">
                    <div class="layui-card top-card">
                        <div class="layui-card-header">
                            推荐列表
                        </div>
                        <div class="layui-card-body">
                            <div class="layui-carousel" id="index_carousel" lay-filter="index_carousel">
                                <div carousel-item="">
                                    {% for each_cour in cour_list %}
                                        <div>
                                            <img src="/static/media/{{ each_cour.cour_image }}">
                                            <p>{{ each_cour.cour_name }}</p>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'assets/js/jquery-1.10.2.js' %}"></script>
<script src="{% static 'assets/js/jquery.metisMenu.js' %}"></script>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script src="{% static 'assets/js/layui/nav.js' %}"></script>
<script src="{% static 'assets/js/layui/stu_index.js' %}"></script>
</body>

</html>

templates/student/learning.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
</head>

<body>
<div class="layui-layout layui-layout-admin">

    {#    TOP NAV#}
    {% include 'nav/top_nav_stu.html' %}
    {#    TOP NAV#}

    {#    LEFT NAV#}
    {% include 'nav/left_nav_stu.html' %}
    {#    LEFT NAV#}

    <div class="layui-body layui-bg-gray">
        {% csrf_token %}
        <input type="hidden" name="cour_id" value="{{ cour_id }}">
        <div style="padding: 10px">
            <fieldset class="layui-elem-field layui-field-title">
                <legend>[{{ sect_tag }}]{{ sect_name }}</legend>
            </fieldset>
        </div>
        <div class="layui-row layui-col-space15" style="padding: 20px">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-header">
                        课程内容
                    </div>
                    <div class="layui-card-body">
                        {% autoescape off %}
                            {{ sect_text }}
                        {% endautoescape %}
                    </div>
                </div>

                <div class="layui-card">
                    <div class="layui-card-header">
                        课程资源
                    </div>
                    <div class="layui-card-body">
                        <p align="center">
                            <video id="sect_video" width="800" controls preload>
                                <source src="/static/{{ sect_media }}" type="video/mp4"/>
                            </video>
                        </p>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script src="{% static 'assets/js/jquery-1.10.2.js' %}"></script>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script src="{% static 'assets/js/layui/learn.js' %}"></script>
</body>

</html>

templates/student/my_course.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    {% include 'nav/head.html' %}
    <link rel="stylesheet" href="{% static 'assets/css/layout/card_list.css' %}"/>

</head>

<body>
<div class="layui-layout layui-layout-admin">

    {#    TOP NAV#}
    {% include 'nav/top_nav_stu.html' %}
    {#    TOP NAV#}

    {#    LEFT NAV#}
    {% include 'nav/left_nav_stu.html' %}
    {#    LEFT NAV#}

    <div class="layui-body layui-bg-gray">
        <div id="item_number" class="layui-hide">{{ item_number }}</div>
        {% csrf_token %}

        <div style="padding: 10px">
            <fieldset class="layui-elem-field layui-field-title">
                <legend>全部课程</legend>
            </fieldset>
        </div>

        <div class="layui-fluid">
            <div class="layui-row layui-col-space12">
                {% for each in cour_list %}
                    <div class="layui-col-md12">
                        <div class="layui-card cour-item" onclick="view_page({{ each.course.id }})">
                            <div class="layui-card-header layui-bg-green">
                                {{ each.course.cour_name }}
                            </div>
                            <div class="layui-card-body" style="min-height: 75px">
                                <img src="/static/media/{{ each.course.cour_image }}"
                                     style="height: 70px; width: 100px; position: absolute">
                                <div style="margin-left: 140px">简介:</div>
                                <div style="margin-left: 140px">
                                    {{ each.course.cour_description }}
                                </div>
                            </div>
                            <div class="layui-progress" lay-showpercent="true">
                                <div class="layui-progress-bar" lay-percent="{{ each.percentage }}%"></div>
                            </div>
                        </div>

                    </div>

                {% endfor %}
            </div>
            <div id="lay-page" style="margin-right: 20px"></div>
        </div>
    </div>

</div>

<script src="{% static 'assets/js/jquery-1.10.2.js' %}"></script>
<script src={% static 'layui/layui.all.js' %}></script>
<script src="{% static 'assets/js/jquery.metisMenu.js' %}"></script>
<script src="{% static 'assets/js/layui/stu_my_course.js' %}"></script>

</body>

</html>

templates/student/recommend.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'nav/head.html' %}
</head>
<body>
<table lay-filter="recommend">
    <thead>
    <tr>
        <th lay-data="{field:'username', width:100}">课程名称</th>
        <th lay-data="{field:'experience', width:100}">创建教师</th>
        <th lay-data="{field:'sign'}">课程分类</th>
    </tr>
    </thead>
    <tbody>
    {% for each_cour in cour_list %}
    <tr>
        <td>{{ each_cour.cour_name }}</td>
        <td>{{ each_cour.cour_create_tch.tch_name }}</td>
        <td>{{ each_cour.get_cour_type_display }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
<script src="{% static 'layui/layui.all.js' %}"></script>
<script>
    var table = layui.table;

    table.init('recommend', {
        height: 315 //设置高度
        , limit: 10
    });
</script>
</html>